language: go

go:
  - tip

sudo: required

before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
 
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  # - sudo chmod +x ./.codecov_test.sh
  # - sudo ./.codecov_test.sh  # Run code coverage test
  
after_success:
  # - bash <(curl -s https://codecov.io/bash)
