language: go

go:
  - tip
before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
 
script:
  - ./.codecov_test.sh  # Run code coverage test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  # - $HOME/gopath/bin/goveralls -service=travis-ci
